// ============================================================
// data.js — Central mock data store for FoodRescue platform
// ============================================================

const FoodRescueData = {

  // --- FOOD LISTINGS ---
  listings: [
    {
      id: 'l001',
      emoji: '🍛',
      name: 'Dal Rice Combo',
      description: 'Freshly cooked dal tadka with steamed rice. 3 servings available.',
      donor: 'Campus Canteen – Block C',
      donorId: 'd001',
      category: 'meals',
      tags: ['veg', 'vegan'],
      price: 0,
      originalPrice: 60,
      isFree: true,
      quantity: 3,
      claimed: 0,
      distance: 0.3,
      pickupStart: '18:00',
      pickupEnd: '19:30',
      urgent: true,
      rating: 4.7,
      ratingCount: 23,
      postedAt: new Date(Date.now() - 20 * 60 * 1000),
    },
    {
      id: 'l002',
      emoji: '🥖',
      name: 'Assorted Bread Loaves',
      description: 'Whole wheat and multigrain loaves from today\'s bake. Perfect for sandwiches.',
      donor: 'Heritage Bakery',
      donorId: 'd002',
      category: 'bakery',
      tags: ['veg'],
      price: 20,
      originalPrice: 80,
      isFree: false,
      quantity: 8,
      claimed: 3,
      distance: 0.8,
      pickupStart: '19:00',
      pickupEnd: '20:30',
      urgent: false,
      rating: 4.9,
      ratingCount: 47,
      postedAt: new Date(Date.now() - 45 * 60 * 1000),
    },
    {
      id: 'l003',
      emoji: '🍱',
      name: 'Veg Thali Set',
      description: 'Complete thali with 2 rotis, sabzi, dal, rice and salad.',
      donor: 'Annapoorna Restaurant',
      donorId: 'd003',
      category: 'meals',
      tags: ['veg'],
      price: 30,
      originalPrice: 120,
      isFree: false,
      quantity: 6,
      claimed: 2,
      distance: 1.2,
      pickupStart: '21:00',
      pickupEnd: '22:00',
      urgent: false,
      rating: 4.6,
      ratingCount: 18,
      postedAt: new Date(Date.now() - 60 * 60 * 1000),
    },
    {
      id: 'l004',
      emoji: '🥗',
      name: 'Fresh Garden Salad Box',
      description: 'Mixed greens, cucumber, cherry tomatoes, tofu. Allergen-free. 4 boxes.',
      donor: 'GreenBowl Café',
      donorId: 'd004',
      category: 'veg',
      tags: ['veg', 'vegan', 'allergen-free'],
      price: 0,
      originalPrice: 90,
      isFree: true,
      quantity: 4,
      claimed: 1,
      distance: 0.6,
      pickupStart: '17:30',
      pickupEnd: '18:30',
      urgent: true,
      rating: 4.8,
      ratingCount: 12,
      postedAt: new Date(Date.now() - 15 * 60 * 1000),
    },
    {
      id: 'l005',
      emoji: '🧁',
      name: 'Muffins & Pastry Box',
      description: 'Assorted muffins (chocolate, blueberry, banana) and croissants. 10 pieces.',
      donor: 'Heritage Bakery',
      donorId: 'd002',
      category: 'bakery',
      tags: ['veg'],
      price: 50,
      originalPrice: 200,
      isFree: false,
      quantity: 2,
      claimed: 0,
      distance: 0.8,
      pickupStart: '20:00',
      pickupEnd: '21:00',
      urgent: false,
      rating: 4.9,
      ratingCount: 31,
      postedAt: new Date(Date.now() - 90 * 60 * 1000),
    },
    {
      id: 'l006',
      emoji: '🍲',
      name: 'Sambar & Idli Pack',
      description: 'South Indian breakfast pack – 6 idlis with sambar and chutney.',
      donor: 'Murugan Mess',
      donorId: 'd005',
      category: 'meals',
      tags: ['veg', 'vegan'],
      price: 0,
      originalPrice: 50,
      isFree: true,
      quantity: 5,
      claimed: 4,
      distance: 1.5,
      pickupStart: '10:30',
      pickupEnd: '11:30',
      urgent: false,
      rating: 4.5,
      ratingCount: 9,
      postedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    },
  ],

  // --- DONORS ---
  donors: [
    {
      id: 'd001',
      name: 'Campus Canteen – Block C',
      type: 'canteen',
      address: 'NIT Campus, Block C, Neelankarai',
      rating: 4.7,
      totalDonations: 148,
      verified: true,
    },
    {
      id: 'd002',
      name: 'Heritage Bakery',
      type: 'bakery',
      address: '12, ECR Road, Neelankarai',
      rating: 4.9,
      totalDonations: 312,
      verified: true,
    },
    {
      id: 'd003',
      name: 'Annapoorna Restaurant',
      type: 'restaurant',
      address: '5, Bazaar St, Palavakkam',
      rating: 4.6,
      totalDonations: 94,
      verified: true,
    },
    {
      id: 'd004',
      name: 'GreenBowl Café',
      type: 'cafe',
      address: '88, OMR, Sholinganallur',
      rating: 4.8,
      totalDonations: 67,
      verified: false,
    },
    {
      id: 'd005',
      name: 'Murugan Mess',
      type: 'mess',
      address: '3, Temple Road, Neelankarai',
      rating: 4.5,
      totalDonations: 203,
      verified: true,
    },
  ],

  // --- USER SESSION (mock) ---
  currentUser: null,
  reservations: [],

  // --- IMPACT METRICS ---
  impact: {
    mealsSaved: 4280,
    kgRescued: 2140,
    co2Saved: 1920,
    activeDonors: 312,
    activeUsers: 8400,
    weeklyData: [
      { day: 'Mon', meals: 85, waste: 15 },
      { day: 'Tue', meals: 110, waste: 10 },
      { day: 'Wed', meals: 95, waste: 20 },
      { day: 'Thu', meals: 130, waste: 8 },
      { day: 'Fri', meals: 160, waste: 12 },
      { day: 'Sat', meals: 200, waste: 5 },
      { day: 'Sun', meals: 175, waste: 6 },
    ],
    monthlyData: [
      { month: 'Jan', meals: 1200 },
      { month: 'Feb', meals: 1450 },
      { month: 'Mar', meals: 1800 },
      { month: 'Apr', meals: 2100 },
      { month: 'May', meals: 2800 },
      { month: 'Jun', meals: 4280 },
    ],
  },

  // --- RECENT ACTIVITY (for dashboard) ---
  activityLog: [
    { id: 'a001', item: 'Dal Rice Combo', donor: 'Campus Canteen', time: '18:30', status: 'completed', savedKg: 0.8 },
    { id: 'a002', item: 'Bread Loaves ×2', donor: 'Heritage Bakery', time: '19:15', status: 'completed', savedKg: 1.2 },
    { id: 'a003', item: 'Veg Thali', donor: 'Annapoorna Restaurant', time: '21:00', status: 'pending', savedKg: 0.6 },
    { id: 'a004', item: 'Salad Box', donor: 'GreenBowl Café', time: '18:00', status: 'completed', savedKg: 0.4 },
    { id: 'a005', item: 'Muffin Box', donor: 'Heritage Bakery', time: '20:30', status: 'cancelled', savedKg: 0 },
  ],

  // --- NOTIFICATIONS ---
  notifications: [
    { id: 'n001', text: 'New listing: Dal Rice Combo is free near you!', time: '2 min ago', read: false },
    { id: 'n002', text: 'Your reservation at Heritage Bakery is confirmed.', time: '1 hr ago', read: false },
    { id: 'n003', text: 'GreenBowl Café posted a salad box — pick up by 6:30 PM.', time: '3 hr ago', read: true },
  ],
};

// Expose globally
window.FoodRescueData = FoodRescueData;
